// Generated by CoffeeScript 1.6.3
module.exports.MessageBus = require('notice').hub({
  ticks: {
    master: {
      interval: 1000
    }
  },
  manager: {
    authenticate: function(username, password, callback) {
      console.log({
        AUTHENTICATE: {
          u: username,
          p: password
        }
      });
      return callback(null, {});
    },
    listen: {
      port: 20002
    }
  },
  error: {
    keep: 100
  }
});
