// Generated by CoffeeScript 1.6.3
module.exports.MessageBus = require('notice').hub({
  manager: {
    authenticate: {
      username: 'admin',
      password: ''
    },
    listen: {
      port: 20002
    }
  },
  error: {
    keep: 100
  }
});
