// Generated by CoffeeScript 1.6.3
module.exports.CapsuleEmitter = require('notice').client({
  capsule: {
    request: {
      nondescript: false
    },
    health: {
      nondescript: true
    }
  }
});
