// Generated by CoffeeScript 1.4.0
var notice, os;

os = require('os');

notice = require('notice').create('example message generator');

module.exports = {
  stats: function() {
    return notice.info.normal('status update');
  }
};

notice.use(function(payload, next) {
  var fName, _i, _len, _ref;
  payload.platform || (payload.platform = {});
  _ref = ['hostname', 'type', 'platform', 'arch', 'release'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    fName = _ref[_i];
    payload.platform[fName] = os[fName]();
  }
  return next();
});

notice.use(function(payload, next) {
  var fName, _i, _len, _ref;
  payload.specs || (payload.specs = {});
  _ref = ['cpus', 'totalmem', 'networkInterfaces'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    fName = _ref[_i];
    payload.specs[fName] = os[fName]();
  }
  return next();
});

notice.use(function(payload, next) {
  var fName, _i, _len, _ref;
  payload.stats || (payload.stats = {});
  _ref = ['loadavg', 'uptime', 'freemem'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    fName = _ref[_i];
    payload.stats[fName] = os[fName]();
  }
  return next();
});

notice.use(function(msg, next) {
  console.log(JSON.stringify(msg.content));
  return next();
});
