// Generated by CoffeeScript 1.6.3
var MessageBus;

MessageBus = require('./server/message_bus').MessageBus;

exports.start = function() {
  return MessageBus.create({
    title: 'Message Bus Title',
    uuid: 1
  }, function(error, hub) {
    return console.log(hub);
  });
};
