// Generated by CoffeeScript 1.6.3
var Client, MessageBus;

MessageBus = require('./server/message_bus').MessageBus;

Client = require('dinkum').Client;

exports.start = function(callback) {
  return MessageBus.create({
    title: 'Message Bus Title',
    uuid: 1,
    listen: {
      secret: '∆',
      adaptor: 'socket.io',
      port: 10001
    },
    cache: {
      'preloaded-key': {}
    },
    tools: {
      elastic: Client.create({
        transport: 'http',
        port: 9200
      })
    }
  }, function(error, hub) {
    if (error != null) {
      return callback(error);
    }
    hub.use({
      title: 'initializer',
      description: "First middleware is usefull for filtering builtin control capsules."
    }, function(next, capsule, traveral) {
      if (capsule.$$control != null) {
        return next.cancel();
      }
      return next();
    });
    return hub.use({
      title: 'hot swap slot',
      description: "Second middleware to play with."
    }, function(next, capsule, traversal) {
      console.log(capsule);
      return next();
    });
  });
};
